name: tests-lambda

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install test dependencies
        run: npm install --save-dev

      - name: Run Jest Tests
        run: npm test
