name: tests-lambda

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install test dependencies
        run: npm install --save-dev

      - name: Run Jest Tests
        run: npm test
        id: run_test
  # This job only runs if the previous job (test) fails
  check_and_merge:
    name: Check and Merge
    needs: test # Requires successful completion of 'test' job
    runs-on: ubuntu-latest
    if: ${{ failure() == false }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for failing tests
        run: |
          if [[ ${{ job.test.conclusion == 'failure' }} ]]; then
            echo "${{ job.test.conclusion }}"
            echo "Tests are failing. Merge is blocked."
            exit 1
          fi

      - name: Allow merge
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Tests passed. Pull Request can be merged."
            })
